### ISSUE TITLE
Rest-deployment.yaml fails due to OOM Killed

### ISSUE THREAD

**Issue by Mionsz** [openebs/mayastor-docs#95]
Please update the resources available on you official webpage as the resources that are being set for the resources is hugely to low, not only for rest-deployment but also for other components. When working with such resources they like to fail on large workloads and this for sure gives people the bad feeling that Mayastor is incomplete.

Referring to: https://mayastor.gitbook.io/introduction/quickstart/deploy-mayastor
In site header: REST
Link: https://raw.githubusercontent.com/openebs/mayastor-control-plane/v1.0.4/deploy/rest-deployment.yaml

There you've got:
```yaml
      containers:
        - name: rest
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
```

In our case the minimum required setup for the REST Deployment (Pod) to get out of `OOMKill` loop was: 
```yaml
      containers:
        - name: rest
          resources:
            limits:
              cpu: 1500m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 256Mi
```

And the above was only to get out of the Mayastor deployment stage. 

Lab-Environment, Kubernetes is a bare metal kubespray deployment:
```yaml
kubernetes: "v1.25.3"
nodes:
- name: node_group_1
  count: 4
  linux_distro: "Ubuntu 22.04"
  hardware:
    cpu_type: "Intel Xeon ICX"
    cpu_count: 1
    ram: "512GB"
    drives:
    - device: "nvme0"
      size: "349.32GB"
    - device "sda"
      size: "256GB"
- name: node_group_2
  count: 4
  linux_distro: "Ubuntu 22.04"
  hardware:
    cpu_type: "Intel Xeon ICX"
    cpu_count: 2
    ram: "1024GB"
    drives:
    - device: "nvme0"
      size: "1.46TB"
    - device: "nvme1"
      size: "1.46TB"
    - device: "nvme2"
      size: "1.46TB"
    - device: "nvme3"
      size: "1.46TB"
    - device: "sda"
      size: "447GB"
```
